# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#test comment

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:  
- task: Docker@2
  inputs:
    containerRegistry: 'cu19registry'
    repository: 'app-dotnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'